config/routes.rb
::Refinery::Application.routes.draw do
  resources :categories, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :categories, :except => :show do
      resources :products
      collection do
        post :update_positions
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  include Rails.application.routes.url_helpers 
  #default_url_options[:host] = request.host_with_port

  
  acts_as_indexed :fields => [:name]

  validates :name, :presence => true, :uniqueness => true
  
  
  belongs_to :parent, :class_name => "Category", :foreign_key => "parent_id" 
  has_many :children, :class_name => "Category", :foreign_key => "parent_id"
    
  has_and_belongs_to_many :products
  has_and_belongs_to_many :banners
  
  # Docs for acts_as_nested_set https://github.com/collectiveidea/awesome_nested_set
  acts_as_nested_set :dependent => :destroy # rather than :delete_all
  
  def title
    name
  end
  
  def url
    category_products_path(id)
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::BaseController

    crudify :category,
            :conditions => nil,            
            :include => [:parent],
            :title_attribute => 'name', :xhr_paging => true

    def create
          # if the position field exists, set this object as last object, given the conditions of this class.
          if Category.column_names.include?("position")
            params[:category].merge!({
              :position => ((Category.maximum(:position)||-1) + 1)
            })
          end

          if (@category = Category.create(params[:category])).valid?
            
              flash[:notice] = t('refinery.crudify.created', :what => @category.name)
        
              if @category.parent.present?
                if @category.parent.products.present?
                  flash[:notice] += " Please be aware that the '#{@category.parent.name}' category has products attached to it. Please re-assign these."
                end
              end                         
              
              redirect_to admin_categories_path            
            
          else            
              render :action => 'new'            
          end
    end
    
    def update
      
      if @category.update_attributes(params[:category])
        
        if @category.parent.present?
          if @category.parent.products.present?
            flash[:notice] = "Please be aware that the '#{@category.parent.name}' category has products attached to it. Please re-assign these."
          end
        end
        
        redirect_to admin_categories_path
      end
        
    end
    
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :find_all_categories
  before_filter :find_page

  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @category in the line below:
    present(@page)
  end

  def show
    @category = Category.find(params[:id])

    # redirect_to category_products_path(@category)
    
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @category in the line below:
    present(@page)
  end

protected

  def find_all_categories
    @categories = Category.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/categories").first
  end

end

app/views/admin/categories/_actions.html.erb
<ul>
  <% if Admin::CategoriesController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_categories_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_category_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::CategoriesController.sortable? and Category.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Categories"),
                 admin_categories_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Categories"),
                 admin_categories_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/categories/_categories.html.erb
<%= will_paginate @categories %>
<%= render :partial => "sortable_list" %>

app/views/admin/categories/_category.html.erb
<li class='clearfix record' id="<%= dom_id(category) -%>">
  <div class='clearfix'>
	  <span class='title'>
	    <%= category.name %>
	    <span class="preview">&nbsp;</span>
	  </span>
	  <span class='actions'>
	    <%= link_to refinery_icon_tag("application_go.png"), category_path(category),
	        :title => t('.view_live_html'),
	        :target => "_blank" %>
	    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_category_path(category),
	         :title => t('.edit') %>
	    <%= link_to refinery_icon_tag("delete.png"), admin_category_path(category),
	        :class => "cancel confirm-delete",
	        :title => t('.delete'),
	        :confirm => t('message', :scope => 'shared.admin.delete', :title => category.name),
	        :method => :delete %>
	  </span>
  </div>
	
  <!-- This nested ul added for the tree section -->
  <ul class='nested'>    
	<%= render :partial => 'category', :collection => category.children %> 
  </ul>
</li>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @category,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest'  -%>
  </div>
  
  <div class='field'>
    <%= f.label :parent_id -%>
	<!-- <%#= f.collection_select :parent_id, Category.order(:name), :id, :name, :prompt => "-- Select --"  -%> -->

	<%= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" }, :include_blank => true %>	
  </div>

  <div class='field'>
    <div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
      <ul id='page_parts'>
        <% [:description].each_with_index do |part, part_index| %>
          <li class='ui-state-default<%= ' ui-state-active' if part_index == 0 %>'>
            <%= link_to part.to_s.titleize, "##{part}" %>
          </li>
        <% end %>
      </ul>

      <div id='page_part_editors'>
        <% [:description].each do |part| %>
          <div class='page_part' id='<%= part %>'>
            <%= f.text_area part, :rows => 20, :class => 'wymeditor widest' -%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.categories.category'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @category.name)
              } %>
<% end -%>

app/views/admin/categories/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @categories.any? %>
  <!-- <div class='pagination_container'> -->
    <%= render :partial => 'categories' %>
  <!-- </div> -->
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/categories/_sortable_list.html.erb
<ul id='sortable_list'>
  <!-- <%#= render :partial => 'category', :collection => @categories %> -->
  <%= render :partial => 'category', :collection => @categories.select{|p| p.parent_id.nil?}  %>
</ul>
<!-- <%#= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %> -->
<%= render :partial => "/shared/admin/sortable_list",
           :locals => {:continue_reordering => !!local_assigns[:continue_reordering]} %>

app/views/admin/categories/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/categories/index.html.erb
<section id='records' class='tree'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<!-- <%#= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::CategoriesController.sortable? and Category.count > 1 %> -->
<%= render :partial => "/shared/admin/make_sortable",
           :locals => {:tree => true} if @categories.many? -%>

app/views/admin/categories/new.html.erb
<%= render :partial => "form" %>

app/views/categories/index.html.erb
<% content_for :body_content_left do %>
  <ul id="categories">
    <% @categories.each do |category| %>
      <li>
        <%= link_to category.name, category_path(category) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/categories/show.html.erb
<% content_for :body_content_title do %>
  <%= @category.name %>
<% end %>

<% content_for :body_content_left do %>
  <section>
    <h1>Name</h1>
    <p>
      <%=raw @category.name %>
    </p>
  </section>
  <section>
    <h1>Parent</h1>
    <p>
      <%=raw @category.parent %>
    </p>
  </section>
<% end %>

<% content_for :body_content_right do %>
  <aside>
    <h2><%= t('.other') %></h2>
    <ul id="categories">
      <% @categories.each do |category| %>
        <li>
          <%= link_to category.name, category_path(category) %>
        </li>
      <% end %>
    </ul>
  </aside>
<% end %>

<%= render :partial => "/shared/content_page" %>